<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CryptoPlatform.Worker-58a6038c-df37-4d53-ada8-f766431e1e1e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CryptoPlatform.Application\CryptoPlatform.Application.csproj" />
    <ProjectReference Include="..\CryptoPlatform.Security\CryptoPlatform.Security.csproj" />
    <ProjectReference Include="..\CryptoPlatform.Audit\CryptoPlatform.Audit.csproj" />
    <ProjectReference Include="..\CryptoPlatform.Crypto.Abstractions\CryptoPlatform.Crypto.Abstractions.csproj" />
    <ProjectReference Include="..\CryptoPlatform.Persistence\CryptoPlatform.Persistence.csproj" />
  </ItemGroup>
</Project>
