// <auto-generated />
using System;
using CryptoPlatform.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoPlatform.Persistence.Migrations
{
    [DbContext(typeof(CryptoPlatformDbContext))]
    [Migration("20260921075318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysApplication", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("app_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("IpWhitelist")
                        .HasColumnType("text")
                        .HasColumnName("ip_whitelist");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique()
                        .HasDatabaseName("uk_application_app_id");

                    b.ToTable("sys_application", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysApplicationSecret", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_used_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("secret_hash");

                    b.Property<int>("SecretVersion")
                        .HasColumnType("int")
                        .HasColumnName("secret_version");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_app_secret_application");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_app_secret_status");

                    b.ToTable("sys_application_secret", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_id");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("audit_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("current_hash");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int")
                        .HasColumnName("duration_ms");

                    b.Property<string>("KeyId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key_id");

                    b.Property<int?>("KeyVersion")
                        .HasColumnType("int")
                        .HasColumnName("key_version");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("operation");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("operator_id");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("operator_name");

                    b.Property<string>("OperatorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("operator_type");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("request_id");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("result_code");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("source_ip");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id");

                    b.HasIndex("AuditId")
                        .IsUnique()
                        .HasDatabaseName("uk_audit_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_timestamp");

                    b.HasIndex("AppId", "Timestamp")
                        .HasDatabaseName("ix_audit_app_time");

                    b.HasIndex("KeyId", "Timestamp")
                        .HasDatabaseName("ix_audit_key_time");

                    b.HasIndex("Operation", "Timestamp")
                        .HasDatabaseName("ix_audit_operation");

                    b.ToTable("sys_audit_log", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysConfig", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("config_key");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("config_value");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("uk_config_key");

                    b.ToTable("sys_config", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysCryptoDevice", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_name");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("endpoint");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint")
                        .HasColumnName("error_count");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("LastHealthAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_health_at");

                    b.Property<string>("Model")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("model");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("provider_type");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("uk_device_id");

                    b.HasIndex("ProviderType", "Status")
                        .HasDatabaseName("ix_device_provider");

                    b.ToTable("sys_crypto_device", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysIdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("http_method");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("request_hash");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("request_path");

                    b.Property<string>("ResponseBodyHash")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("response_body_hash");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("int")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_expires");

                    b.HasIndex("AppId", "HttpMethod", "RequestPath", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uk_idempotency");

                    b.ToTable("sys_idempotency_record", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKey", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentVersion")
                        .HasColumnType("int")
                        .HasColumnName("current_version");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DestroyedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("destroyed_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("KeyType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key_type");

                    b.Property<string>("KeyUsage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("key_usage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerAppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("owner_app_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("uk_key_id");

                    b.HasIndex("KeyType", "KeyUsage")
                        .HasDatabaseName("ix_key_type_usage");

                    b.HasIndex("OwnerAppId", "Status")
                        .HasDatabaseName("ix_key_owner_status");

                    b.HasIndex("OwnerAppId", "KeyType", "Status")
                        .HasDatabaseName("ix_key_owner_type_status");

                    b.ToTable("sys_key", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKeyAuthorization", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("permissions");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AppId", "Status")
                        .HasDatabaseName("ix_key_auth_app_status");

                    b.HasIndex("KeyId", "AppId")
                        .IsUnique()
                        .HasDatabaseName("uk_key_auth");

                    b.HasIndex("KeyId", "Status")
                        .HasDatabaseName("ix_key_auth_key_status");

                    b.ToTable("sys_key_authorization", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKeyVersion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("activated_at");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedRequestId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("created_request_id");

                    b.Property<string>("DestroyResult")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("destroy_result");

                    b.Property<DateTime?>("DestroyedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("destroyed_at");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("device_id");

                    b.Property<string>("EncryptedKeyMaterial")
                        .HasColumnType("longtext")
                        .HasColumnName("encrypted_key_material");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("fingerprint");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("key_id");

                    b.Property<string>("ProviderKeyRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("provider_key_ref");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("provider_type");

                    b.Property<string>("PublicKeyMaterial")
                        .HasColumnType("text")
                        .HasColumnName("public_key_material");

                    b.Property<DateTime?>("RotatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("rotated_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.Property<long>("UsageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("usage_bytes");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("usage_count");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_key_version_fingerprint");

                    b.HasIndex("ProviderKeyRef")
                        .HasDatabaseName("ix_key_version_provider_ref");

                    b.HasIndex("KeyId", "Status")
                        .HasDatabaseName("ix_key_version_status");

                    b.HasIndex("KeyId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("uk_key_version");

                    b.HasIndex("ProviderType", "DeviceId")
                        .HasDatabaseName("ix_key_version_provider");

                    b.ToTable("sys_key_version", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysPermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("permission_code");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("permission_name");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id");

                    b.HasIndex("PermissionCode")
                        .IsUnique()
                        .HasDatabaseName("uk_permission_code");

                    b.ToTable("sys_permission", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("description");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("role_name");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasDatabaseName("uk_role_code");

                    b.ToTable("sys_role", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysSecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("app_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("detected_at");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("event_type");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("handled_at");

                    b.Property<string>("Handler")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("handler");

                    b.Property<string>("HandlingResult")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("handling_result");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("operator_id");

                    b.Property<string>("RelatedKeyId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("related_key_id");

                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("request_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("source_ip");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_event_detected");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uk_event_id");

                    b.HasIndex("EventType", "Status")
                        .HasDatabaseName("ix_event_type_status");

                    b.HasIndex("Severity", "Status")
                        .HasDatabaseName("ix_event_severity");

                    b.ToTable("sys_security_event", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("locked_until");

                    b.Property<int>("LoginFailCount")
                        .HasColumnType("int")
                        .HasColumnName("login_fail_count");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<sbyte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uk_user_username");

                    b.ToTable("sys_user", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysUserRole", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_role_user");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("uk_user_role");

                    b.ToTable("sys_user_role", (string)null);
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysApplicationSecret", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.SysApplication", null)
                        .WithMany("Secrets")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKeyAuthorization", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.SysKey", null)
                        .WithMany("Authorizations")
                        .HasForeignKey("KeyId")
                        .HasPrincipalKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKeyVersion", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.SysKey", null)
                        .WithMany("Versions")
                        .HasForeignKey("KeyId")
                        .HasPrincipalKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysUserRole", b =>
                {
                    b.HasOne("CryptoPlatform.Domain.Entities.SysUser", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysApplication", b =>
                {
                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysKey", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CryptoPlatform.Domain.Entities.SysUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
